### PR TITLE
Rescue Etc.getgrgid so that the fallback code path is possible

### PR DESCRIPTION
**Pull request by sodabrew**

### CODE REVIEW

**Comment by sodabrew** [comment]
There's a fallback code path if the group name cannot be found, but it can't run if Etc.getgrgid raises:

``` ruby
      def current_group
        group_obj = Etc.getgrgid
        make_valid_group_name(group_obj ? group_obj.name : "dummygroup")
      end
```

**Comment by larskanis** [comment]
On which operating system does getgrpid raise an exception?

**Comment by sodabrew** [comment]
On OS X if the group doesn't have a name set, (maybe because it's a NetInfo group?)

**Comment by larskanis** [comment]
Thank you @sodabrew ! I just released rake-compiler-dock-0.5.2 with your change.

**Pull request merged**
