### PR TITLE
[draft] ruby 3.2 support

### PR DESCRIPTION
**Pull request by flavorjones**
This is a naive attempt (based on #81) to add Ruby 3.2.0 support using the recent rc1.

I've built the x86_64-linux image on my dev machine, and used it to build Nokogiri libraries that support 3.2 and pass all the tests.

The changes I made to Nokogiri are:

```patch
diff --git a/.cross_rubies b/.cross_rubies
index b585a0e..5c42e9c 100644
--- a/.cross_rubies
+++ b/.cross_rubies
@@ -30,3 +30,11 @@
 3.1.0:x86-mingw32
 3.1.0:x86_64-darwin
 3.1.0:x86_64-linux
+3.2.0:aarch64-linux
+3.2.0:arm-linux
+3.2.0:arm64-darwin
+3.2.0:x64-mingw-ucrt
+3.2.0:x86-linux
+3.2.0:x86-mingw32
+3.2.0:x86_64-darwin
+3.2.0:x86_64-linux
diff --git a/rakelib/extensions.rake b/rakelib/extensions.rake
index aabdb3e..ef67f9a 100644
--- a/rakelib/extensions.rake
+++ b/rakelib/extensions.rake
@@ -168,7 +168,7 @@ def allowed_dlls
         "libc.so.6",
         "libdl.so.2", # on old dists only - now in libc
       ].tap do |dlls|
-        dlls << "libpthread.so.0" if ver < "2.6.0"
+        dlls << "libpthread.so.0" if ver < "2.6.0" or ver >= "3.2.0"
       end
     when AARCH_LINUX_PLATFORM_REGEX
       [
```

I'm not sure why `libpthread.so.0` shows up as a shared object dependency, when it hasn't been one since 2.5. @larskanis any ideas on that? It seems OK, the tests pass.

### CODE REVIEW

**Comment by larskanis** [comment]
Looks like a dependency issue in the makefiles on Macos. Everytime I added a new ruby version I got such dependency issues that appear only when cross compiling and often only with "make -j".

**Comment by larskanis** [comment]
`libpthread` was introduced as a dependency of C-exts due to requirements of the MJIT implementation. Now in Ruby-3.2 both MJIT as well as YJIT received a major refactoring, so I guess that's the root cause. I did a quick search in the ruby sources, but didn't find the corresponding commit. So I think the changes to nokogiri are OK.

That brings me back to the idea to move these checks from Nokogiri to RCD. I had the plan to introduce a class kind of `RakeCompilerDock::ExtensionDll` that knows how to check the DLL on Windows/Linux/Macos and that knows all the details of our cross ruby versions. It might be added to the Rakefile of Nokogiri and other projects to verify their output. Of course there must be a way to add additional DLLs to the check by subclassing or so.

**Comment by flavorjones** [comment]
I'll see if I can repro and diagnose it without the `-j` option on my local machine.

Re: the DLL checks, I agree it would be nice to have something in rake-compiler-dock (or some other, new gem?), but it's not a blocker. Maybe we can commit to working on that together in 2023, I would love to add checks like this to sqlite3-ruby, for example, but haven't gotten there yet.

If I get this to go green, and can build a Nokogiri on it that passes the tests, I'll merge this (unless you have objections). Then I'll tackle https://github.com/rake-compiler/rake-compiler-dock/issues/71 so I can set up a Nokogiri CI pipeline that will use images generated from RCD head.

**Comment by flavorjones** [comment]
Isolated the issue to building 3.2.0-rc1. Here's the error:

```
x86_64-apple-darwin-clang -dynamic -bundle -o .ext/x86_64-darwin/enc/encdb.bundle enc/encdb.o -L. -L. -L. -pipe  -fstack-protector-strong -pipe  -Wl,-multiply_defined,suppress -Wl,-undefined,dynamic_lookup -bundle_loader './miniruby'   -lpthread  
ld: file not found: ./miniruby
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure where to start to debug this, so parking it here for bit until I've got more time.

**Comment by flavorjones** [comment]
It looks like that patch _does_ fix the build; and the need for it seems to come from https://github.com/ruby/ruby/commit/50d81bf

@kateinoigakukun When building cross-rubies in this project, `miniruby` doesn't seem to get built before it's needed by this change. Do you think this should be handled upstream in Ruby's makefiles, or should we just make sure rake-compiler explicitly builds miniruby first?

**Comment by flavorjones** [comment]
I've opened an issue at https://bugs.ruby-lang.org/issues/19239

**Comment by flavorjones** [comment]
And I've suggested a fix at https://github.com/ruby/ruby/pull/6944

**Comment by flavorjones** [comment]
It's not clear if that fix is going to be accepted upstream, so I'm going to leave the patch in this PR for now and merge it once it goes green again. We can remove it later if it becomes unnecessary.

**Pull request merged**
