### PR TITLE
Use docker's `DRIVER` environment variable, if present

### PR DESCRIPTION
**Pull request by aharpervc**
Now you can use hyperv, etc

### CODE REVIEW

**Comment by larskanis** [comment]
The environment variable of docker-machine is called [MACHINE_DRIVER](https://github.com/docker/machine/blob/master/commands/create.go#L302) , so that I propose this key for rake-compiler-dock as well.

Did you test rake-compiler-dock with hyperv? Did it work? Are there any recommendations for the README file?

**Comment by aharpervc** [comment]
Weird, the release notes for 0.7.0 only mention `DRIVER`, which does work. I was able to get a machine up and running. Full support will require a bit more work, for example, `docker_check.rb` doesn't load in the env correctly (personally I blame docker's shell detection but whatever)

```patch
-      text.scan(/(export |\$Env:)(.+?)(="|=| = ")(.*?)(|\")$/) do |_, key, _, val, _|
+      text.scan(/(export |\$Env:|SET )(.+?)(="|=| = ")(.*?)(|\")$/) do |_, key, _, val, _|
```

**Comment by aharpervc** [comment]
Also, aside from the engine side of things which is semi-working, I'm having an unrelated problem getting docker to actually pull in images (https://github.com/docker/docker/issues/22398).

**Comment by larskanis** [comment]
This is implemented in commit dfcb3f9. Thank you!

**Comment by aharpervc** [comment]
rad 🎉

**Pull request closed without merging**
