### PR TITLE
move `x86_64-linux` to be based on `ubuntu:20.04`

### LINKED ISSUE #120: Drop the math.h patch in a future release
Now that rcd supports musl as a first-class platform, I think we should unwind the changes we made to try to support musl with the gnu build toolchain.

Specifically I'm thinking of the `math.h` patch introduced in 864be5b2 (see #42). There may be other things we did, too, we should inventory the code and commit log.

### PR DESCRIPTION
**Pull request by flavorjones**
Exploration of a solution for #122 

Changes:
- *Remove math.h patch.*
  This should no longer be needed since it existed only to provide some additional compatibility for musl target systems in the "x86_64-linux" gems. Closes #120.
- *Move the `x86_64-linux-gnu` and `x86-linux-gnu` images to be based off `ubuntu:20.04`*
  Remove all manylinux-specific build steps from the dockerfile template.

### CODE REVIEW

**Comment by flavorjones** [comment]
@larskanis I'd love your opinion on this change if you get a few minutes to review.

**Comment by flavorjones** [comment]
I've got a fix for the x86 image almost ready to go.

**Comment by ianks** [comment]
Would this mean that precompiled gems could no longer run on old libc?

**Comment by flavorjones** [comment]
The min glibc version would update from 2.17 to 2.29. What platforms are you targetting?

**Comment by ianks** [comment]
> We will need to update the min glibc version in some way at some point in time. If you can help me understand your requirements maybe we can make better decisions. Ideally I don't want to be supporting ancient systems for new gems and new versions of Ruby (especially if previous rake-compiler-dock images still support those ancient systems), for some definition of "ancient" that is informed by distro EOL and Python manylinux EOL.

I feel somewhat unqualified here, and for me _personally_ I would prefer to be on some ubuntu. But I do know there are companies out there on old un-upgradable servers and I worry we could break things for them... But then again, they can always compile from source so maybe it doesn't matter?

**Comment by flavorjones** [comment]
@ianks Right, end users can still compile their own stuff on older systems if they need to -- there's an escape hatch if you consider rake-compiler-dock to be an _optimization_ and not a _critical requirement_ for gem delivery.

Really, this comes down to: I'm willing to support old systems as long as it doesn't cost much in terms of effort and complexity. But we're at the point where continuing on manylinux2014 has [been hard](https://github.com/rake-compiler/rake-compiler-dock/issues/121) and just [got harder](https://github.com/rake-compiler/rake-compiler-dock/pull/127).

**Comment by ianks** [comment]
Think I agree with you here. My one request would be that we look into the [cross-rs images](https://github.com/cross-rs/cross/blob/main/docker/Dockerfile.aarch64-unknown-linux-gnu.centos), since they've solved a lot of the traditional cross toolchain problems and offer some nice builtin features like qemu emulation, etc

**Comment by flavorjones** [comment]
@ianks I'm happy to chat about cross-rs at some point, but since they are also based on 20.04 (and presumably mostly-compatible) maybe we can move that discussion to a separate issue?

**Comment by flavorjones** [comment]
@larskanis Do you have any thoughts about this change? Unless you have strong objections, I'd like to merge it to make it easier to start testing downstream gems against the snapshot images.

**Review by larskanis — APPROVED** [review]
I never really liked the manylinux base images.  For me it's questionable, if we could compile a gcc package or configure the default one, to build binaries with lower libc requirements.

**Comment by flavorjones** [comment]
Well, maybe we can start with this change, and if people ask for lower glibc requirements we can look into building/configuring the toolchain.

**Pull request merged**
