### PR TITLE
publish image snapshots to ghcr.io

### PR DESCRIPTION
**Pull request by flavorjones**
See #71 for context.

This is a draft to try to publish snapshots of the docker images to ghcr.io for integration testing on other projects.

### CODE REVIEW

**Comment by flavorjones** [comment]
woot!
- action https://github.com/rake-compiler/rake-compiler-dock/actions/runs/3721653404/jobs/6311949466
- published https://github.com/rake-compiler/rake-compiler-dock/pkgs/container/rake-compiler-dock-snapshot

**Comment by flavorjones** [comment]
Note: I don't think the image naming here is completely right, it's different from lars's dockerhub names and also doesn't take into consideration the work @ianks is doing at #79 to build arm64 host images.

**Comment by ianks** [comment]
> Note: I don't think the image naming here is completely right, it's different from lars's dockerhub names and also doesn't take into consideration the work @ianks is doing at #79 to build arm64 host images.

As far as #79 is concerned, it shouldn't affect the naming at all (since the image is automatically selected by Docker via the `--platform` flag).

**Comment by flavorjones** [comment]
> the image is automatically selected by Docker via the --platform flag

Ah! OK, I get it.

**Pull request merged**
